# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
pool: Default
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
- stage: SSD
  displayName: Send Events
  jobs:
  - job: Events
    displayName: Events
    steps:   
    - task: CmdLine@2
      inputs:
        script: 'docker run -v $(Build.SourcesDirectory):/home/scanner/source/ docker.io/opsmx11/ssd-scanner-cli:d5bb0ed-4   --scanners=semgrep,openssf,trivy --trivy-scanners=codelicensescan,codesecretscan  --artifact-type=file --source-code-path="/home/scanner/source/"   --repository-url="https://sbraj002@dev.azure.com/sbraj002/OpsMx/_git/OpsMx"   --branch="master"   --build-id="1234"   --offline-mode=false --upload-url="https://ssd.adani.opsmx.net" --ssd-token="eyJhbGciOiJSUzI1NiIsImtpZCI6IjdmYWRiOTk0LTI2MjktNDE0Ny04NzljLTljNWQ2MDQxZDNlOSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJPcHNNeCIsImF1ZCI6WyJzc2Qub3BzbXguaW8iXSwiZXhwIjoxNzcyNjI4NDYxLCJuYmYiOjE3Mzg2NzMyNjEsImp0aSI6ImFiY2QxMjM0Iiwic3NkLm9wc214LmlvIjp7InR5cGUiOiJpbnRlZ3JhdGlvbi92MSIsIm9yZ0lEIjoiMjhjYWI1ODUtZjgyNS00NDk4LTk5NjctMDVlZmE1ZDViMzk0IiwidGVhbUlEIjoiYjRmMWQwM2QtNTNhNy00ZWEzLTk0NmItMjFjOWIyYTMxZjhiIn19.oUg5BlWBUzF8qhqtFAR2DmnmO9f_a_SZUtAho4k8QRS6I3drChri2zAYFEvdNsOAx4A_HRBnyFiGGKIUxqZCm1kMykyhYyhEq6GKM4QN4wYMUNXU1kfF5gwpKwsrlEwDXtUTjVNlEmiHeLhd6SalDhiPf1OAn0pm5CYXLpxW2uqmQ-nSKXH40CeZbUbQ2yYkLH96zlYjV-dLwzEgC0b6Z4I0NdE1Tm8KaubmLcSr6XmO4BLkVRILIBeZFWyp_dtantHDN6SEi5GEkwQXCd2wovDn24Njdb1GWRO44m1gQSVL_dr8Gt_CDlzbRhkWzkFSdKRbszc3omHvnoaIan-MwQ"'